### ISSUE TITLE
jspm endpoint config github - configuration encrypted and attached to repository (TravisCI)

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#449]
does it make sense to attach this configuration to project directory/repository?

specifically, I am getting `GitHub rate limit reached` very frequently last few days, like [this](https://travis-ci.org/djindjic/jspm-sample.tk/builds/48889424#L290) (don't now why). After all, I'm not sure does it possible to run `jspm endpoint config` and enter github username and pass/token over travis build, or user/pass could be additionl arguments of this command line?

**Comment by guybedford** [comment]
Yes there is an issue for this at https://github.com/jspm/jspm-cli/issues/190.

**Comment by sochka** [comment]
I have really strange build problems.

Travis build - https://travis-ci.org/kpi-wdc/wdc/builds/53413009
I have this .travis.yml: 
```
language: node_js
sudo: false
cache:
  directories:
  - ~/.jspm
  - node_modules
  - .tmp/bower_components
before_install:
- npm install jspm
- jspm config endpoints.github.auth $GH_TOKEN
matrix:
  include:
  - node_js: '0.12'
    env: PRODUCTION=true
  - node_js: '0.12'
    env: SEND_COVERAGE=true
  - node_js: '0.10'
  - node_js: iojs
```

`$GH_TOKEN` variable is set manually through travis' web interface.
